//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("webchat.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid captcha words, please try again!.
        /// </summary>
        public static string CaptchaError {
            get {
                return ResourceManager.GetString("CaptchaError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your nickname must be composed only of alphanumeric characters and underscores!.
        /// </summary>
        public static string CharNickError {
            get {
                return ResourceManager.GetString("CharNickError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room names may be composed only of alphanumeric characters and underscores!.
        /// </summary>
        public static string CharRoomsError {
            get {
                return ResourceManager.GetString("CharRoomsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A database error occurred, please try again later!.
        /// </summary>
        public static string DatabaseError {
            get {
                return ResourceManager.GetString("DatabaseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to default.
        /// </summary>
        public static string DefaultRoom {
            get {
                return ResourceManager.GetString("DefaultRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to global_user_list.
        /// </summary>
        public static string GlobalUserListKey {
            get {
                return ResourceManager.GetString("GlobalUserListKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your nickname must be at least 3 characters long!.
        /// </summary>
        public static string LengthNickError {
            get {
                return ResourceManager.GetString("LengthNickError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type your nickname here.
        /// </summary>
        public static string NickPlaceHolder {
            get {
                return ResourceManager.GetString("NickPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a valid nickname in order to connect!.
        /// </summary>
        public static string RequiredNickError {
            get {
                return ResourceManager.GetString("RequiredNickError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join rooms.
        /// </summary>
        public static string RoomsPlaceHolder {
            get {
                return ResourceManager.GetString("RoomsPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to room_user_list.
        /// </summary>
        public static string RoomUserListKey {
            get {
                return ResourceManager.GetString("RoomUserListKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This nick is already in use!.
        /// </summary>
        public static string UniqueNickError {
            get {
                return ResourceManager.GetString("UniqueNickError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to webchat.users.
        /// </summary>
        public static string UsersEventChannel {
            get {
                return ResourceManager.GetString("UsersEventChannel", resourceCulture);
            }
        }
    }
}
